MACOSX_SDK_VERSION:        # [osx]
  - "11.0"                # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 11.0                      # [osx and x86_64]
