MACOSX_SDK_VERSION:        # [osx]
  - "26"                # [osx]

args_to_build:
 - "--target-cpu=arm64" # [arm64]
 - "--target-cpu=arm64" # [aarch64]

BUILD_PLATFORM:
    - linux-aarch64 # [aarch64]
    - linux-ppc64le # [ppc64le]
